### ISSUE TITLE
Fix MLH banner on navbar for mobile site

### ISSUE THREAD

**Issue by Monty1029** [Monty1029/CUHackingWebsite#16]

**Comment by bkzhang** [comment]
Where should it go? The top right is the mobile drop-down navigation and the logo is on the top right, should it just be placed under the drop-down nav?

**Comment by arungalva** [comment]
You could add the mlh logo to the navbar itself. What do you think of something like this ?

![image](https://cloud.githubusercontent.com/assets/12630802/22605240/fce86e4e-ea1c-11e6-9d9d-869ba08400d5.png)

**Comment by bkzhang** [comment]
Looks good, but seems like it takes up a lot of space and I'm not too sure about the rules regarding the banner. @Monty1029 ? What should we do?

**Comment by Monty1029** [comment]
How about adding the banner to the left of the mobile dropdown menu?

**Comment by bkzhang** [comment]
So like this? Also 2nd version of hover is better than first imo.

<img width="807" alt="screen shot 2017-02-03 at 7 06 40 pm" src="https://cloud.githubusercontent.com/assets/13925815/22613148/ec17e42e-ea43-11e6-8e21-35d03ab68a61.png">
<img width="807" alt="screen shot 2017-02-03 at 7 06 08 pm" src="https://cloud.githubusercontent.com/assets/13925815/22613152/f0576514-ea43-11e6-8038-c95e76af9f25.png">
<img width="807" alt="screen shot 2017-02-03 at 7 05 33 pm" src="https://cloud.githubusercontent.com/assets/13925815/22613154/f16d7fb0-ea43-11e6-8875-ee14a03c87dd.png">

**Comment by Monty1029** [comment]
Go with the last image.
