### ISSUE TITLE
"Apply Now" button is misplaced when using Safari on some Macs

### ISSUE THREAD

**Issue by Monty1029** [Monty1029/CUHackingWebsite#31]

**Comment by arungalva** [comment]
Can you give me more details ?

**Comment by Monty1029** [comment]
Like on some Macs when people use safari, then the Apply Now button shows up below the main section (it shows up in the "Hack at Canada's Capital University") section.

**Comment by bkzhang** [comment]
Closing this for now since the button is gone and I never experienced the problem on my mac. Reopen if it appears next year I guess.
